
const WALK_KNEAD_KNOCK_MOTOR_STRUCT_AUTO AutoFunction4[] = 
{	

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER     ,0,KNEAD_STOP        ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,   _3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER     ,0,KNEAD_STOP_AT_MIN ,1,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER     ,0,KNEAD_STOP_AT_MIN ,1,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP_AT_MIN ,1,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0}, 
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP_AT_MIN ,1,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP_AT_MIN ,1,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0}, 
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP        ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK         ,0,KNEAD_STOP        ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK         ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP        ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP        ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER    ,0,KNEAD_STOP_AT_MIN  ,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  

  //ÉÏÌá   ÈàÄó¿í¶È£ºÕ­ Õ­ Èà
  //1
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,20,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20}, 
  //·ï³Ø ÈàÄó
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,80,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  //ÏÂÐÐµ½¼ç
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  //¼ç²¿ÈàÄó  ¶¨µãÖ¸Ñ¹
          {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,100,KNEAD_RUN ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0}, 
{BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP_AT_MIN ,2,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},           
          {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
          
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
          
  //2
   //·ï³ØÈàÄó
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},  
  //
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,80,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  //ÏÂÐÐ¼ç
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP  ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  //¼ç²¿ÈàÄó  ¶¨µãÖ¸Ñ¹
          {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,100,KNEAD_RUN ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0}, 
{BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP_AT_MIN ,2,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0}, 

          {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
          
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
          {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
          
  //3 ÉÏÐÐ·ï³ØÈà
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_Ear      ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,10,KNEAD_STOP             ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},  
  //Ear
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,60,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_Ear,0,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0}, 
  //NeckMed
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0}, 
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_RUN_MEDRUBBING ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_2_10,0,KNEAD_RUN_MEDRUBBING ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_4_10,0,KNEAD_RUN_MEDRUBBING ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_9_10,0,KNEAD_RUN_MEDRUBBING ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK      ,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_4_10,0,KNEAD_RUN_MEDRUBBING ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK      ,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_2_10,0,KNEAD_RUN_MEDRUBBING ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK      ,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_1_10,0,KNEAD_RUN_MEDRUBBING ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK      ,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER    ,0,KNEAD_RUN_MEDRUBBING ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0}, 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed     ,0,KNEAD_RUN_MEDRUBBING ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK        ,40,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0}, 
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_Ear,0,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,60,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
    {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,60,KNEAD_RUN_MEDRUBBING,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},

  
  //ÏÂÑ¹µ½¼ç¼×¹Ç£¬Èà
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_9 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  //ÇÃ»÷  »Ö¸´
  // µÚ 1 ½Ú MIN/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_4,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_2,0},

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP ,0,0,SPEED_1,_3D_PROGRAM,_3D_1,_3D_SPEED_4,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_2,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},

  // µÚ 2 ½Ú MED/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_2,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_1,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_3,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_2,0},

  // µÚ 3 ½Ú MAX/////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_2,_3D_SPEED_4,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_1,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_4,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_2,0},

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_STOP ,0,0,SPEED_2,_3D_PROGRAM,_3D_1,_3D_SPEED_4,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_4,0},  
  {BACK_SUB_MODE_KNOCK,WALK_LOCATE_PARK        ,20,KNEAD_STOP       ,0,KNOCK_RUN ,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_4,0},

//end 
//Èà
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_3_10,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP       ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_6_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},

  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,60,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_KNEAD,WALK_SHOULDER_WAIST_6_10,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
    {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_9_10,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
    
 // {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,3,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_WAVELET,WALK_LOCATE_PARK,100,KNEAD_RUN,0,KNOCK_RUN,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,1,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP_AT_MIN    ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_STOP_AT_MIN    ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},

//PRESS 3D
/*
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP     ,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
 




  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  //{BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK,0,KNEAD_STOP           ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  

  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,20},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,20,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,20},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
*/
//3D--2////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
/*
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_3_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},

  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MED,2,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  
*/
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,40,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_PARK        ,0,KNEAD_STOP                ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_1_10 ,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_KNEAD  ,WALK_LOCATE_PARK,0,KNEAD_RUN_STOP_AT_MIN,2,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
  
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  
  //»¬¼ç  ¼ç²¿¸§Ãþ  ÈàÄó¿í¶È£ºÕ­
   {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_2_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},



  //»¬¼ç  ¼ç²¿¸§Ãþ  ÈàÄó¿í¶È£ºÖÐ
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MED,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_5_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
 
  //»¬¼ç  ¼ç²¿¸§Ãþ  ÈàÄó¿í¶È£º¿í
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER,0 ,KNEAD_STOP_AT_MAX,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP     ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},
  {BACK_SUB_MODE_PRESS,WALK_SHOULDER_WAIST_4_10,0,KNEAD_STOP ,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_4,0},
  
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER    ,0,KNEAD_STOP_AT_MIN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_WEAKEST,_3D_SPEED_3,0},
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER    ,0 ,KNEAD_STOP,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_4,0},

//
  //¾±²¿À´»ØÈàÄó		
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_3,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed ,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_5,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK    ,40,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  

 {BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
 //{BACK_SUB_MODE_KNEAD,WALK_LOCATE_ABSULATE,0,KNEAD_RUN         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0},
 
  //´ê±³  
  //{BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,_3D_4,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_6_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //WALK_SHOULDER_WAIST_5_10  WALK_LOCATE_SHOULDER
  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_3_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},




  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_6_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  //WALK_SHOULDER_WAIST_5_10  WALK_LOCATE_SHOULDER
  {BACK_SUB_MODE_RUBBING,WALK_SHOULDER_WAIST_3_10,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},



  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_PressNeck,0,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_RUBBING,WALK_LOCATE_ABSULATE,WAIST_POSITION,KNEAD_RUN_RUBBING,0,KNOCK_STOP,0,0,SPEED_4,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},

  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_1,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_NeckMed,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGER,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},

  {BACK_SUB_MODE_SOFT_KNOCK,WALK_SHOULDER_WAIST_1_10,0,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,1,4,SPEED_1,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,1,4,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,8,2,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MED,0,KNOCK_RUN_STOP,8,2,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_SOFT_KNOCK,WALK_LOCATE_PARK,50,KNEAD_STOP_AT_MIN,0,KNOCK_RUN_STOP,9,1,SPEED_3,_3D_PROGRAM,AXIS_STRONGEST,_3D_SPEED_7,0},	
  
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_SHOULDER,0,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK,20,KNEAD_RUN,0,KNOCK_STOP,0,0,SPEED_2,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_7,0},	
 
 
  {BACK_SUB_MODE_KNEAD,WALK_LOCATE_PARK ,0,KNEAD_STOP_AT_MIN ,1,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_MIDDLE,_3D_SPEED_4,0}, 
  {BACK_SUB_MODE_PRESS,WALK_LOCATE_SHOULDER ,0,KNEAD_STOP         ,0,KNOCK_STOP,0,0,SPEED_3,_3D_PROGRAM,AXIS_WEAKER,_3D_SPEED_4,0},

};
